apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: mainissuer
spec:
  acme:
    email: kreato@kreato.dev
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
